# Generated by Django 3.0.6 on 2020-05-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('sch_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_frame', models.CharField(max_length=32)),
                ('description', models.TextField(default='')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'black'), (2, 'red'), (3, 'blue'), (4, 'green')], default=4)),
                ('is_done', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
