# Generated by Django 3.0.6 on 2020-05-23 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='userApp',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='userApp',
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='userApp.User'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
