# Generated by Django 3.0.6 on 2020-05-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20200523_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='content',
            new_name='act_content',
        ),
    ]
