# Generated by Django 3.0.6 on 2020-05-23 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=32, null=True)),
                ('telephone', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('user_type', models.IntegerField(choices=[(1, 'student'), (2, 'instructor'), (3, 'dean'), (4, 'admin')])),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userApp.User')),
            ],
        ),
    ]
