# Generated by Django 3.0.6 on 2020-05-30 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userApp', '0002_auto_20200524_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_num', models.CharField(max_length=32)),
                ('room_status', models.PositiveSmallIntegerField(choices=[(1, '空闲'), (2, '使用中'), (3, '暂不外借')], default=1)),
                ('user', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userApp.User')),
            ],
        ),
    ]
