# Generated by Django 3.0.6 on 2020-05-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='room_status',
            field=models.IntegerField(choices=[(1, '空闲'), (2, '使用中'), (3, '暂不外借')], default=1),
        ),
    ]
