# Generated by Django 3.0.6 on 2020-06-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomApi', '0002_auto_20200530_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='room_num',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
